name: Convert to UTF-16LE ( Game )

on:
  push:
    paths:
      - "tf2c_strings/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "tf2c_strings/**"
  workflow_dispatch:

jobs:
  convert:
    name: Convert to UTF-16LE ( Game )
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Convert UTF-8 to UTF-16LE
        run: ./convert.sh tf2c_strings

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf2c_strings_utf16le
          path: converted_tf2c_strings/
